// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test_api.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// UnaryMethodRequest - request message for UnaryMethod rpc.
type UnaryMethodRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnaryMethodRequest) Reset()         { *m = UnaryMethodRequest{} }
func (m *UnaryMethodRequest) String() string { return proto.CompactTextString(m) }
func (*UnaryMethodRequest) ProtoMessage()    {}
func (*UnaryMethodRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77683351be7bc655, []int{0}
}

func (m *UnaryMethodRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnaryMethodRequest.Unmarshal(m, b)
}
func (m *UnaryMethodRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnaryMethodRequest.Marshal(b, m, deterministic)
}
func (m *UnaryMethodRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnaryMethodRequest.Merge(m, src)
}
func (m *UnaryMethodRequest) XXX_Size() int {
	return xxx_messageInfo_UnaryMethodRequest.Size(m)
}
func (m *UnaryMethodRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnaryMethodRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnaryMethodRequest proto.InternalMessageInfo

func (m *UnaryMethodRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

// BinaryMethodRequest - request message for BinaryMethod rpc.
type BinaryMethodRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BinaryMethodRequest) Reset()         { *m = BinaryMethodRequest{} }
func (m *BinaryMethodRequest) String() string { return proto.CompactTextString(m) }
func (*BinaryMethodRequest) ProtoMessage()    {}
func (*BinaryMethodRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77683351be7bc655, []int{1}
}

func (m *BinaryMethodRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BinaryMethodRequest.Unmarshal(m, b)
}
func (m *BinaryMethodRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BinaryMethodRequest.Marshal(b, m, deterministic)
}
func (m *BinaryMethodRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BinaryMethodRequest.Merge(m, src)
}
func (m *BinaryMethodRequest) XXX_Size() int {
	return xxx_messageInfo_BinaryMethodRequest.Size(m)
}
func (m *BinaryMethodRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BinaryMethodRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BinaryMethodRequest proto.InternalMessageInfo

func (m *BinaryMethodRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

// BinaryMethodResponse - response message for BinaryMethod rpc.
type BinaryMethodResponse struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BinaryMethodResponse) Reset()         { *m = BinaryMethodResponse{} }
func (m *BinaryMethodResponse) String() string { return proto.CompactTextString(m) }
func (*BinaryMethodResponse) ProtoMessage()    {}
func (*BinaryMethodResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77683351be7bc655, []int{2}
}

func (m *BinaryMethodResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BinaryMethodResponse.Unmarshal(m, b)
}
func (m *BinaryMethodResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BinaryMethodResponse.Marshal(b, m, deterministic)
}
func (m *BinaryMethodResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BinaryMethodResponse.Merge(m, src)
}
func (m *BinaryMethodResponse) XXX_Size() int {
	return xxx_messageInfo_BinaryMethodResponse.Size(m)
}
func (m *BinaryMethodResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BinaryMethodResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BinaryMethodResponse proto.InternalMessageInfo

func (m *BinaryMethodResponse) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func init() {
	proto.RegisterType((*UnaryMethodRequest)(nil), "qrpc.test.api.UnaryMethodRequest")
	proto.RegisterType((*BinaryMethodRequest)(nil), "qrpc.test.api.BinaryMethodRequest")
	proto.RegisterType((*BinaryMethodResponse)(nil), "qrpc.test.api.BinaryMethodResponse")
}

func init() { proto.RegisterFile("test_api.proto", fileDescriptor_77683351be7bc655) }

var fileDescriptor_77683351be7bc655 = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x49, 0x2d, 0x2e,
	0x89, 0x4f, 0x2c, 0xc8, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2d, 0x2c, 0x2a, 0x48,
	0xd6, 0x03, 0x09, 0xea, 0x25, 0x16, 0x64, 0x4a, 0x49, 0xa7, 0xe7, 0xe7, 0xa7, 0xe7, 0xa4, 0xea,
	0x83, 0x25, 0x93, 0x4a, 0xd3, 0xf4, 0x53, 0x73, 0x0b, 0x4a, 0x2a, 0x21, 0x6a, 0x95, 0xd4, 0xb8,
	0x84, 0x42, 0xf3, 0x12, 0x8b, 0x2a, 0x7d, 0x53, 0x4b, 0x32, 0xf2, 0x53, 0x82, 0x52, 0x0b, 0x4b,
	0x53, 0x8b, 0x4b, 0x84, 0x04, 0xb8, 0x98, 0x4b, 0x33, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38,
	0x83, 0x40, 0x4c, 0x25, 0x75, 0x2e, 0x61, 0xa7, 0x4c, 0x62, 0x14, 0x6a, 0x70, 0x89, 0xa0, 0x2a,
	0x2c, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0xc5, 0x54, 0x69, 0xb4, 0x86, 0x91, 0x8b, 0x3d, 0x24, 0xb5,
	0xb8, 0xc4, 0x31, 0xc0, 0x53, 0xc8, 0x83, 0x8b, 0x1b, 0xc9, 0x19, 0x42, 0x8a, 0x7a, 0x28, 0x5e,
	0xd0, 0xc3, 0x74, 0xa2, 0x94, 0x98, 0x1e, 0xc4, 0x5b, 0x7a, 0x30, 0x6f, 0xe9, 0xb9, 0x82, 0xbc,
	0x25, 0x14, 0xce, 0xc5, 0x83, 0x6c, 0xbf, 0x90, 0x12, 0x9a, 0x51, 0x58, 0x7c, 0x21, 0xa5, 0x8c,
	0x57, 0x0d, 0xc4, 0x03, 0x46, 0x9e, 0x5c, 0x1c, 0x20, 0xd7, 0x1a, 0x81, 0x9c, 0x6b, 0xcb, 0xc5,
	0x0d, 0xb6, 0x0d, 0x6a, 0x07, 0x0e, 0xb7, 0xe0, 0x72, 0xa3, 0x93, 0x72, 0x94, 0x62, 0x7a, 0x66,
	0x49, 0x46, 0x69, 0x92, 0x5e, 0x72, 0x7e, 0xae, 0x7e, 0x72, 0x62, 0x71, 0x46, 0x79, 0x62, 0x7a,
	0x7e, 0x9e, 0x3e, 0xc8, 0x15, 0xfa, 0x20, 0x57, 0xe8, 0x17, 0x24, 0x25, 0xb1, 0x81, 0x35, 0x19,
	0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x88, 0xaf, 0xa7, 0x32, 0xde, 0x01, 0x00, 0x00,
}
