package generator

const handlerTemplate = `
{{- "" -}}
// Code generated by protoc-gen-go. DO NOT EDIT.
// source: {{ .SourceFile }}

package handler

import (
	"context"

	"github.com/cashwagon/qrpc/pkg/qrpc"
	"github.com/golang/protobuf/proto"

	{{- range .Imports }}
	{{ .Alias }} "{{ .Package }}"
	{{- end }}
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the qrpc package it is being compiled against.
const _ = qrpc.SupportPackageIsVersion{{ .GeneratedCodeVersion }}

{{- range .Services }}
{{- $service := .Name -}}
{{- $clientInt := ($service | sprintf "%sClient") -}}
{{- $clientType := ($service | unexport | sprintf "%sClient") -}}
{{- $serverInt := ($service | sprintf "%sServer") }}

{{- if (.Methods | isAnyBinaryMethods) }}

// {{ $clientInt }} is the client API for {{ $service }} service.
type {{ $clientInt }} interface {
	{{- range (.Methods | filterBinaryMethods) }}
	{{ .Name }}(context.Context, *{{ .OutType }}) error
	{{- end }}
}

type {{ $clientType }} struct {
	cc *qrpc.ClientConn
}

func New{{ $clientInt }}(cc *qrpc.ClientConn) {{ $clientInt }} {
	cc.SetService("qrpc.test.api.{{ $service }}.out")
	return &{{ $clientType }}{cc}
}

{{- range (.Methods | filterBinaryMethods ) }}

func (c *{{ $clientType }}) {{ .Name }}(ctx context.Context, in *{{ .OutType }}) error {
	data, err := proto.Marshal(in)
	if err != nil {
		return err
	}

	return c.cc.Invoke(ctx, qrpc.Message{
		Method: "{{ .Name }}",
		Data:   data,
	})
}
{{- end }}
{{- end }}

// {{ $serverInt }} is the server API for {{ $service }} service.
type {{ $serverInt }} interface {
	{{- range .Methods }}
	{{ .Name }}(context.Context, *{{ .InType }}) error
	{{- end }}
}

func Register{{ $serverInt }}(s *qrpc.Server, srv {{ $serverInt }}) {
	s.RegisterService(&_{{ $service }}_serviceDesc, srv)
}

{{- range .Methods }}

func _{{ $service }}_{{ .Name }}_Handler(srv interface{}, ctx context.Context, msg []byte) error {
	in := new({{ .InType }})

	if err := proto.Unmarshal(msg, in); err != nil {
		return err
	}

	return srv.({{ $serverInt }}).{{ .Name }}(ctx, in)
}
{{- end }}

var _{{ $service }}_serviceDesc = qrpc.ServiceDesc{
	ServiceName: "qrpc.test.api.{{ $service }}.in",
	HandlerType: (*{{ $serverInt }})(nil),
	Methods: []qrpc.MethodDesc{
		{{- range .Methods }}
		{
			MethodName: "{{ .Name }}",
			Handler: _{{ $service }}_{{ .Name }}_Handler,
		},
		{{- end }}
	},
}
{{- end }}
`
